"""relationship bin blogs and users

Revision ID: f3b7c658e2c4
Revises: d1e1a2f58210
Create Date: 2026-02-16 09:55:22.917489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b7c658e2c4'
down_revision: Union[str, Sequence[str], None] = 'd1e1a2f58210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'author_id')
    # ### end Alembic commands ###
